org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
loom_version=1.16-SNAPSHOT

#Mod
archives_base_name=copycats
maven_group=com.copycatsplus
mod_authors=Lysine, Bennyboy1695, Redcat_XVIII
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=All the copycats you've ever wanted, combined into a single mod!
mod_name=Create: Copycats+
mod_license=All Rights Reserved
mod_credits=The Create: Addon Hub Discord
mod_issues=https://github.com/copycats-plus/copycats/issues
mod_url=https://github.com/copycats-plus/copycats

# Build target: 26.1.2 or 26.2
target_version=26.1.2

fabric_loader_version=0.19.3
create_version_range=>=6.0.9-1 <6.0.10

#Common Properties
doDryRun=false
mixin_extras_version=0.4.1
jei_common_version=19.21.0.247
emi_common_version=1.1.22
sodium_curse_id=6382651
diagonal_mods_version=8.0.5
ponder_version=1.0.66

#Fabric Properties
create_fabric_version=6.0.9-3
create_fabric_range=>=6.0.9
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_fabric_version=19.21.0.247
config_port_version=8.0.0
continuity_curse_version=5962874
jade_fabric_curse_id=5339230
athena_fabric_curse_id=5629396
indium_fabric_curse_id=5493195
sodium_fabric_version=mc1.20.1-0.5.11
extended_cogwheels_fabric_version=2.1.1-1.20.1-0.5.1.f-fabric
spark_fabric_curse_id=4738953
moonlight_curse_fabric_id=5975796
vertical_slabs_curse_fabric_id=5691542
additionalplacements_fabric_curse_id=6057817
