architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/copycats.accesswidener")
}

dependencies {
    modImplementation files(rootProject.create_fly_jar)
    modCompileOnly("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")
    annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
}
